sverrirs/jekyll-paginate-v2

lib/jekyll-paginate-v2/autopages/defaults.rb

Hi, I found typo (extra ` character) in your default tag title.

AutoPage tag default typo fix

---

README-GENERATOR.md
lib/jekyll-paginate-v2/generator/paginationModel.rb
lib/jekyll-paginate-v2/generator/utils.rb

Jekyll support [extensionless permalinks](https://jekyllrb.com/docs/permalinks/#extensionless-permalinks) when you omit the slash (/) from the end of your permalink setting. This patch adds support to the same capabilities to jekyll-paginate-v2.
Just omit the slash from the end of your permalink in the front matter, to generate .html files instead of folders.
```
pagination:
enabled: true
permalink: '/page:num'
```

Add support for extensionless permalinks

---

lib/jekyll-paginate-v2/generator/paginationPage.rb

The current implementation, will only generate html files from their respective templates. This PR adds an option for setting the generated page's file extension.
For example the following page template would generate a set of json files, based on the user's pagination settings.
```
---
layout: null
pagination:
enabled: true
extension: json
---
{
"pages": [
{% for post in paginator.posts %}
{
"Title": "{{ post.title }}"
},
{% endfor %}
]
}
```

Create an option for setting a page file extension

---

lib/jekyll-paginate-v2/generator/paginationModel.rb

The thing being asked for a `date` property is a `Jekyll::Document`.
Not all documents have a date (though most tend to), so this adds a
cautionary check.
As discussed in #29, I'm not sure of how idiomatic this type of check is. I have tested locally that it no longer crashes when hitting this code when paginating collections which don't have dates. I've also successfully built your three example sites in `examples/`.
Despite this, I'm not sure if that proves I haven't introduced a regression for #12 and 9fe7e3f0420, so you might want to double check that as I'm unfamiliar with that particular issue..
Fixes #29.

Check if document has a date property before querying.

---

lib/jekyll-paginate-v2/generator/utils.rb

This compares `Date` (_YYYY-MM-DD_ only) and `Time` fields by doing a `to_datetime` first (if possible) so the comparison doesn't fail for custom sort date fields. It also checks for `nil`s since comparing it to e.g. a `Time` would also fail.
Should fix/help with issue #43

Check for nils, convert to DateTime before comparing

---

lib/jekyll-paginate-v2/generator/paginationModel.rb

In cases where there are no posts (fresh site) or all the posts are hidden, no `index.html` is generated at the document root, leading to 404 errors from many/most hosting providers. This patch makes paginate-v2 always generate at least 1 page.
This fixes issue #52

Generate at least one page, issue #52

---

lib/jekyll-paginate-v2/generator/utils.rb

This just moves the check for nils before comparing strings during sort, e.g.
~~~yaml
---
title: Hello
custom: abcd
---
~~~
~~~yaml
---
title: World
---
~~~
will currently fail if sort_field is `custom`.

Check for nil strings during sort

---

.rubocop.yml
lib/jekyll-paginate-v2/autopages/utils.rb
lib/jekyll-paginate-v2/generator/paginationGenerator.rb
lib/jekyll-paginate-v2/generator/paginationIndexer.rb
lib/jekyll-paginate-v2/generator/paginationModel.rb
lib/jekyll-paginate-v2/generator/utils.rb

Since `Enumerable#each` is faster than `for` loops. :slightly_smiling_face: 
Ref: https://github.com/JuanitoFatas/fast-ruby#enumerableeach-vs-for-loop-code

Replace for loops with Enumerable#each

---

lib/jekyll-paginate-v2/autopages/autoPages.rb
lib/jekyll-paginate-v2/generator/paginationGenerator.rb

This allows pagination of tags and categories created by other generators. See #59

AutoPages support for tags/categories created by other generators

---

README.md
examples/01-typicalblog/_includes/header.html
examples/02-category/_includes/header.html
examples/02-category/cars/_posts/2016-10-18-Porsche-918-Spyder.md
examples/02-category/categories/blackandwhite.md
examples/03-tags/_config.yml
examples/03-tags/_fantasy/all/terry-pratchet-diary-2017.md
examples/03-tags/_includes/header.html
examples/03-tags/_layouts/home.html
lib/jekyll-paginate-v2/autopages/defaults.rb
lib/jekyll-paginate-v2/autopages/pages/categoryAutoPage.rb
lib/jekyll-paginate-v2/autopages/pages/collectionAutoPage.rb
lib/jekyll-paginate-v2/autopages/pages/tagAutoPage.rb
lib/jekyll-paginate-v2/autopages/utils.rb

This adds a `special_characters` option to `autopages` to allow the use of spaces and other characters in tags, etc. Basically, if specified, this just omits the slugify step. See #20 
~~~yaml
autopages:
tags:
special_characters: true
categories:
special_characters: true
collections:
special_characters: true
~~~

Add special_characters option to autopages tags, cats, and colls

---

examples/02-category/categories/pm.md
examples/02-category/categories/protosports.md
lib/jekyll-paginate-v2/generator/paginationIndexer.rb
lib/jekyll-paginate-v2/generator/utils.rb

This adds `pagination` options for filtering tags/categories using `all` (and) or `any` (or). See #63.
`category_filter: any|all`: filter for categories
`tag_filter: any|all`: filter for tags
`filter: any|all`: fallback/default if neither of the above is present
Well, actually, it just checks for "all", anything else is considered "any", and the part before the underscore is the `config_key`, so `locale_filter` is also there.
The default is `all` (and) per the current behavior.
This also merges "tag" and "tags", "category" and "categories", etc. during processing so that values in either/both of the variants are used, whether they are strings or arrays.
Example will be at http://localhost:4000/porsche+mercedes/ under `examples/02-category`.

AND/OR filters for tags, categories, and locales

---

lib/jekyll-paginate-v2/generator/paginationModel.rb

It is wasteful calling `to_i` on a result that is already an integer

Array#size returns integer

---

lib/jekyll-paginate-v2/generator/paginationModel.rb

As per the recommendation,
```
Pages must have 'pagination: enabled: true' in their front-matter for pagination to work.
```
Pages with the following front matter **should not** be paginated:
```
---
title: Foo
pagination:
enabled: yes
category: foobar
---
```

Paginate template only if explicitly enabled

---

lib/jekyll-paginate-v2/generator/paginator.rb

`#page_trail` is already defined by `attr_reader`

Remove duplicate method definition

---

lib/jekyll-paginate-v2/generator/paginationPage.rb

Since `PaginationPage` instances are *in-memory-only* objects, they should *ideally* mirror their parent's `relative_path`.
Additional benefits:
- the result for `{{ page.path }}` in the `first_index_page` is the same irrespective of whether pagination is enabled or not
- compute the value once and then refer to the same object thereafter.
- avoids values such as `.html` when `index_pageandext == '.html'`

Set PaginationPage rel_path based on parent page

---

lib/jekyll-paginate-v2/generator/paginationModel.rb
lib/jekyll-paginate-v2/generator/paginationPage.rb

It is a common convention in Ruby to use a method name with a trailing `=` as the "setter method" for a given instance.
Aliasing the current `PaginationPage#set_url` method name for backwards compatibility

Add an alias_method setter for setting urls

---

lib/jekyll-paginate-v2/generator/paginationModel.rb

```ruby
if !bar
foo = 'lorem'
else
foo = bar
end
```
is simplified to:
```ruby
foo = bar || 'lorem'
```

Replace conditional with double pipe operator

---

lib/jekyll-paginate-v2/generator/paginationModel.rb
lib/jekyll-paginate-v2/generator/utils.rb

This is to ensure a proper url when there's an *unconventional* `permalink` defined for the `template_page`
For example, given a `foo/index.html` with the following front matter:
```
---
title: Foo Bar
permalink: foo/bar.html
pagination:
enabled: true
---
```
the following are the `before` and `after` results:
```
first_index_page: /foo/bar.html/index.html
pagination_page: /foo/bar.html/page/:num/index.html
```
```
first_index_page: /foo/index.html
pagination_page: /foo/page/:num/index.html
```
Thoughts?

Compute first_index_page_url from template's url

---

lib/jekyll-paginate-v2/generator/paginationModel.rb

While Jekyll logger may not be suitable to print multi-line messages, simple single-line messages can leverage Jekyll logger's built-in logic in to pad the "topic-key" with trailing spaces

Use Jekyll logger to print simple strings

---

lib/jekyll-paginate-v2/generator/paginationModel.rb

Instead of multiple calls to `newpage.pager.page_path` that return the same value, we can cache the return value in a local variable and use that variable for calculations instead

Cache the value of newpage.pager.page_path in var

---

.codeclimate.yml

No point analyzing the superfluous files..

CodeClimate: Exclude everything not a `lib/**/*.rb`

---

lib/jekyll-paginate-v2/generator/defaults.rb

Currently, `PaginationModel` sets `''` as the fallback basename when it is `nil`. Instead, it should be `index` as expected by `PaginationPage`
Resolves #142

Set 'index' as the default basename of indexpage

---

jekyll-paginate-v2.gemspec

This change is recommended for plugin authors by Jekyll [here](https://jekyllrb.com/news/)

Relaxes Jekyll dependency in gemspec to allow for Jekyll 4.0

---

README-AUTOPAGES.md

I've added slugify options to site config example so new users can get to know that this feature is available. At this moment the only way to find out that there is "slugify" option is to search issues or source code. It's mentioned nowhere (except third example).
**I'm now sure if defaults are correct though**.
If someone is up-to-date with source code, I would really appreciate some verification.

Added slugify options to site config example

---

examples/02-category/README.md
examples/02-category/categories/toyota-or-porsche.md
lib/jekyll-paginate-v2/generator/paginationIndexer.rb
lib/jekyll-paginate-v2/generator/paginationModel.rb
spec/generator/paginationIndexer_spec.rb

The current behaviour when specifying multiple categories, tags and locales on a pagination page is to filter posts that include **all** of these.
For example, this shows all posts with **both** the food and animal categories:
```
pagination:
category: food, animal
```
This pull request adds a `combine: union` option which can change that behaviour to filter posts that have **at least one** of the specified categories, tags and locales.
For example, this shows all posts with **either** the food and animal categories:
```
pagination:
category: food, animal
combine: union
```
I've added a couple of tests and modified the example to demonstrate how to use it. I'm currently using this fork on a site to achieve this. It'd be great to refer to the main repo instead, let me know if there's …

Option to union rather than intersect paginated posts

---

lib/jekyll-paginate-v2/generator/paginationPage.rb

The current behaviour of this plugin involves deleting the initial pagination pages, and then re-adding them as the first paginated page.
In most cases, this page is added back with the internal path set to ".html". The only exception is when the `indexpage` option is provided, the path is changed as a side effect.
This pull request restores the original file path for the first pagination page, which allows any plugin running after pagination to inspect or affect the first page in a sane manner.
The page data as it leaves this plugin is currently, generally:
```
{
"name":".html",
"path":".html",
"url":"/blog/index.html",
...
}
```
This pull request amends the first page to have the following data:
```
{
"name":".html",
"path":"blog/index.html",
"url":"/blog/index.html",
...
}
```
Any …

Improve compatibility with other plugins that access page.path

---

lib/jekyll-paginate-v2/generator/paginationPage.rb

The current behaviour of this plugin involves creating synthetic pages for pagination, based on the initial pagination file.
In all cases, these pages are added back without `page.ext` being set. This causes `page.output_exts` to be empty, which causes the initial page to disappear from `site.html_pages`, and the paginated pages to not appear.
This pull request transfers the original extension to the paginated pages, which allows any plugin running after pagination to inspect or affect the output pages.
The acute case for this behaviour is better compatibility with the cloudcannon-jekyll plugin. I also imagine this will help most plugins that happen to run after pagination.

Retain page extension after pagination

---

README-AUTOPAGES.md
lib/jekyll-paginate-v2/autopages/autoPages.rb

Sorry for the re-submission. I was having trouble with github somehow merging all the commits I'm force pushing automatically, and thus I couldn't keep them separate. Ended up just deleting my fork, reforking and then pushing again. It's working now 😄.
This pull request continues from #179

reduce the verbosity of pagination logging [again]
